### ISSUE TITLE
excel文件git pull更新后, ide的Excelreader里显示的还是原来的

### ISSUE THREAD

**Issue by PalenCent** [obiscr/ExcelReader#1]
没有实时更新

**Comment by PalenCent** [comment]
重启IDE或者关掉项目再打开都没有办法解决

**Comment by obiscr** [comment]
能说一下你的运行环境吗？

IDE版本：
JDK版本：
ExcelReader版本：

**Comment by obiscr** [comment]
非常感谢反馈此问题。但是根据我的测试情况，并没有出现上述的问题。
详细的测试测试过程如下，我是本地修改的。本质上本地和git pull一样的，都是文件的变动。

**CSV 测试**
[](https://obiscr.oss-cn-hongkong.aliyuncs.com/res/ExcelReader/issue/1/issue1_csv.gif?versionId=CAEQUBiBgICeocGNyRciIDcyNmJjMmZiYmEyNzQzNTViODA5NDgxOWI1ZjRiNDRk)

**XLS 测试**
[](https://obiscr.oss-cn-hongkong.aliyuncs.com/res/ExcelReader/issue/1/issue1_xls.gif?versionId=CAEQUBiBgIDeoMGNyRciIGI0YmE2YmU4MTEyOTQxNzA4ZTMwNzM3NGU2YjAwYzIz)

**XLSX 测试**
[](https://obiscr.oss-cn-hongkong.aliyuncs.com/res/ExcelReader/issue/1/issue1_xlsx.gif?versionId=CAEQUBiBgMDsoMGNyRciIDA1YThlYWRjNjg2NTRmYTZiNzg3NmVkMjI3NWQ5Yzk1)

请检查您是否有**重新加载**Excel文件，看能否生效。如果还不能生效的话，请用Excel工具打开
看下 `git pull` 之后文件是否发生了改变。或者检查文件hash值。我推测可能是Excel文件本身哪里出了问题，希望能帮到你，谢谢！

**Comment by PalenCent** [comment]
您好, 抱歉没看到回复, 因为有一段时间没有使用过excelreader了, 今天升级至2.0.6后重新打开了一下对应的excel文件, 显示是最新的, 因此暂且没法复现当时产生的问题, 感谢您的耐心回复!

**Comment by PalenCent** [comment]
您好, 我在使用excelReader2.0.6, Goland 2020.2.3时再次出现了刚才的问题
![image](https://user-images.githubusercontent.com/45139699/117911301-1fd78a00-b310-11eb-933d-7ce33ec46071.png)
![image](https://user-images.githubusercontent.com/45139699/117911319-2a921f00-b310-11eb-9dc3-854b155f8d6b.png)
![image](https://user-images.githubusercontent.com/45139699/117911347-34b41d80-b310-11eb-845b-134d04ebea85.png)
