### ISSUE TITLE
Last .csv column not showing up

### ISSUE THREAD

**Issue by ZXSwire3** [obiscr/ExcelReader#1]
This is how it shows up in IntelliJ IDEA 2023.2.3 (Ultimate Edition)
<img width="754" alt="image" src="https://github.com/obiscr/ExcelReader/assets/19944156/a547cf67-ce7c-4062-a46f-0ad3f02a5dad">
but the actual csv file looks like this
<img width="221" alt="image" src="https://github.com/obiscr/ExcelReader/assets/19944156/4d290eeb-0e4b-4b25-9b30-68af79278fe1">
[test.csv](https://github.com/obiscr/ExcelReader/files/13048460/test.csv)
there doesn't seem to be anything special about this specific csv file because it was happening on every csv file that I tried it on.

**Comment by obiscr** [comment]
Thank you, It will be fixed soon.

**Comment by ZougaRida** [comment]
Yees It drove me nuts why that last column in my csv not showing!

**Comment by obiscr** [comment]
Sorry for being a while late, it'll be fixed in the next version in a few days.

**Comment by obiscr** [comment]
This issue has been fixed, Please update to latest version 2023.11.1, thank you all.
