### ISSUE TITLE
feature request: "Open with default editor"

### ISSUE THREAD

**Issue by The-Alchemist** [obiscr/ExcelReader#10]
We'd like to be able to open a CSV with the regular IntelliJ text editor as well.

Looks like you don't get a choice, there is no "Open with Text Editor" option.  

This feature is essential for putting CSVs in a VCS, because we want to be able to view the raw text before committing.

**Comment by obiscr** [comment]
> We'd like to be able to open a CSV with the regular IntelliJ text editor as well.
> 
> Looks like you don't get a choice, there is no "Open with Text Editor" option.
> 
> This feature is essential for putting CSVs in a VCS, because we want to be able to view the raw text before committing.

Thanks for the feedback.
Yes, at present, csv cannot be displayed when comparing with git. Later versions will consider supporting this.

Temporary workaround:
Step 1: Open **Settings** -> **Editor** -> **File Types**, in the **Recognized File Types** table, find `Excel` and select it. With Excel selected, delete `*.csv` in **File Name Patterns** table.
![image](https://user-images.githubusercontent.com/28687074/156696359-d7ac6dd5-c259-451f-8abb-8b15feb1e23b.png)

Step 2: Also in **Settings** -> **Editor** -> **File Types**, in **Recognized File Types** table, find `CSV/TSV Data` and select it, add `*.csv` to **File Name Patterns** table.
![image](https://user-images.githubusercontent.com/28687074/156696702-d855f02d-f85b-46a3-b418-ed66d6369414.png)

Just save it, the file type should be refreshed automatically, if not, please reopen the current project or restart the IDE.

But there is one inconvenient place to do this. If you want to open csv through the ExcelReader/ExcelEditor plug-in, you can only do it through: select the csv file, and right-click to select "Open As ExcelReader" or "Open As ExcelEditor" to open, it cannot support double-click to open and Search Everywhere to open.
