### ISSUE TITLE
Plugin doesn't display all of the cells

### ISSUE THREAD

**Issue by Danon** [obiscr/ExcelReader#11]
**Describe the bug**

I have an excel that looks like this

```
A | B
A | B
A | B
A | B | C | D | E
A | B | C | D | E
A | B | C | D | E
```

**Expected behavior**
I would expect to see all the cells, but I see only the first two columns

**Screenshots**

![image](https://user-images.githubusercontent.com/13367735/166918749-9340c6fe-ac32-45be-b96d-818069899e35.png)
![image](https://user-images.githubusercontent.com/13367735/166918781-d1362639-5eca-41aa-9de7-cdcfe45ec24e.png)

**Comment by obiscr** [comment]
> **Describe the bug**
> 
> I have an excel that looks like this
> 
> ```
> A | B
> A | B
> A | B
> A | B | C | D | E
> A | B | C | D | E
> A | B | C | D | E
> ```
> 
> **Expected behavior** I would expect to see all the cells, but I see only the first two columns
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/13367735/166918749-9340c6fe-ac32-45be-b96d-818069899e35.png) ![image](https://user-images.githubusercontent.com/13367735/166918781-d1362639-5eca-41aa-9de7-cdcfe45ec24e.png)

Yes, ExcelReader does have this problem. Sorry, there may not be time to revise in the near future. There will be time to fix this issue later.

If you want to use it now, you can temporarily replace it with [ExcelEditor](https://exceleditor.obiscr.com/). ExcelEditor should not have this problem. ExcelEditor is free for a month if you don't want to pay. :D

**Comment by obiscr** [comment]
> **Describe the bug**
> 
> I have an excel that looks like this
> 
> ```
> A | B
> A | B
> A | B
> A | B | C | D | E
> A | B | C | D | E
> A | B | C | D | E
> ```
> 
> **Expected behavior** I would expect to see all the cells, but I see only the first two columns
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/13367735/166918749-9340c6fe-ac32-45be-b96d-818069899e35.png) ![image](https://user-images.githubusercontent.com/13367735/166918781-d1362639-5eca-41aa-9de7-cdcfe45ec24e.png)

This problem will be fixed in the next few days, please pay attention to the plugin update. Thanks!
![image](https://user-images.githubusercontent.com/28687074/174424543-61804929-a675-439b-9eb0-69715af8c1a4.png)

**Comment by obiscr** [comment]
### Update to the following version to fix this problem

| Plugin Version        | IDE Version                                   |
|:-------------|:----------------------------------------------|
| [2022.1.3](https://plugins.jetbrains.com/plugin/14722-excelreader/versions/stable/186834)  | 2022.1 ~ latest |
| [2021.3.4](https://plugins.jetbrains.com/plugin/14722-excelreader/versions/stable/186833)  | 2021.3 ~ 2021.3.2 |
| [2021.2.4](https://plugins.jetbrains.com/plugin/14722-excelreader/versions/stable/186832)  | 2021.2 ~ 2021.2.4 |
| [2021.1.4](https://plugins.jetbrains.com/plugin/14722-excelreader/versions/stable/186831)  | 2021.1 ~ 2021.1.3 |
| [2020.3.4](https://plugins.jetbrains.com/plugin/14722-excelreader/versions/stable/186830)  | 2020.3 ~ 2020.3.4 |
| [2020.2.4](https://plugins.jetbrains.com/plugin/14722-excelreader/versions/stable/186829)  | 2020.2 ~ 2020.2.4 |
| [2020.1.4](https://plugins.jetbrains.com/plugin/14722-excelreader/versions/stable/186828)  | 2020.1 ~ 2020.1.4 |
