### ISSUE TITLE
Update the tool window icon

### ISSUE THREAD

**Issue by mahozad** [obiscr/ExcelReader#14]
What do you think about updating the [tool window icons](https://github.com/obiscr/ExcelReader/tree/main/src/main/resources/icons) (and other excel icons) a little bit?

[Simplifying the lines and making them pixel-perfect](https://jetbrains.design/intellij/principles/icons/#04), making the "X" transparent, aligning it in the trapezoid and make it follow the perspective:

![perspective](https://user-images.githubusercontent.com/29678011/197881659-dae39267-ab1d-4634-89f4-7df40d379c0c.png)

Here is the comparison:

| old | new |
| ---- | ---- |
| ![old](https://user-images.githubusercontent.com/29678011/197882313-d4c35f91-566b-4ff5-adfe-6b7300d73c93.png) | ![new](https://user-images.githubusercontent.com/29678011/197882352-3f0ba878-d818-4a17-b020-5ca2a93aecaf.png) |

SVG icon: ![icon](https://user-images.githubusercontent.com/29678011/197883260-0ce339eb-b2c5-4fa4-af99-da0c5e35214c.svg)

I will be glad to create a pull request if you'd like.

**Comment by obiscr** [comment]
Oh, that's great.  I'm not a professional UI designer. Therefore, the open source icon was adopted at that time, and additional colors were added to it. Thank you, Mahdi. I welcome to create a merge request.

**Comment by mahozad** [comment]
Thanks.

I forked the repository and updated almost all SVG icons.

How can I test the plugin? Running "Run Plugin" or "Run IDE for UI Tests" executes IntelliJ Commercial which requires license or activation code.

**Comment by obiscr** [comment]
Thank you! You can use [IntelliJ Community](https://www.jetbrains.com/idea/download/download-thanks.html?platform=windows&code=IIC) to test. This is free to use.

**Comment by mahozad** [comment]
No problem. I changed the IDE type from `platformType = IU` to `platformType = IC` in gradle.properties:
https://github.com/obiscr/ExcelReader/blob/75b33e0e311b2c2e8f266261059d1364507dea47/gradle.properties#L24

**Comment by obiscr** [comment]
> No problem. I changed the IDE type from `platformType = IU` to `platformType = IC` in gradle.properties:
> 
> https://github.com/obiscr/ExcelReader/blob/75b33e0e311b2c2e8f266261059d1364507dea47/gradle.properties#L24

I saw the PR, and I will deal with it later today or tomorrow.

**Comment by mahozad** [comment]
Thanks.
