### ISSUE TITLE
Compatibility with IntelliJ running JDK11

### ISSUE THREAD

**Issue by ahus1** [obiscr/ExcelReader#18]
**Describe the bug**

I'm the maintainer of the AsciiDoc plugin for IntelliJ. Some of my users used the automatic error reporting that indicated a problem with the ExcelReader plugin. 

The error message:

> java.util.concurrent.ExecutionException: com.intellij.diagnostic.PluginException: Cannot load class com.github.obiscr.excelreader.file.MyExcelNativeFileType (
  error: com/github/obiscr/excelreader/file/MyExcelNativeFileType has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=ExcelReader, id=com.chesterccw.excelreader, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2021.2/plugins/ExcelReader, version=2022.12.1-203.223, package=null), packagePrefix=null, instanceId=53, state=active)
)

The environment: IntelliJ Community Edition 2021.2.2 running Java 11.0.12

As the ExcelReader plugin in version 2022.12.1-203.223 supports IntelliJ versions  2020.3 to 2022.3.2 according to https://plugins.jetbrains.com/plugin/14722-excelreader/versions, and those old versions still use JDK11, see also [this blog post](https://blog.jetbrains.com/platform/2020/09/intellij-project-migrates-to-java-11).

For the plugin I maintain, I added the following settings in the build file, maybe something similar would work for this plugin.

```
java {
  targetCompatibility = "11"
  sourceCompatibility = "11"
}
```

**Comment by obiscr** [comment]
> **Describe the bug**
> 
> I'm the maintainer of the AsciiDoc plugin for IntelliJ. Some of my users used the automatic error reporting that indicated a problem with the ExcelReader plugin.
> 
> The error message:
> 
> > java.util.concurrent.ExecutionException: com.intellij.diagnostic.PluginException: Cannot load class com.github.obiscr.excelreader.file.MyExcelNativeFileType (
> > error: com/github/obiscr/excelreader/file/MyExcelNativeFileType has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0,
> > classLoader=PluginClassLoader(plugin=PluginDescriptor(name=ExcelReader, id=com.chesterccw.excelreader, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2021.2/plugins/ExcelReader, version=2022.12.1-203.223, package=null), packagePrefix=null, instanceId=53, state=active)
> > )
> 
> The environment: IntelliJ Community Edition 2021.2.2 running Java 11.0.12
> 
> As the ExcelReader plugin in version 2022.12.1-203.223 supports IntelliJ versions 2020.3 to 2022.3.2 according to https://plugins.jetbrains.com/plugin/14722-excelreader/versions, and those old versions still use JDK11, see also [this blog post](https://blog.jetbrains.com/platform/2020/09/intellij-project-migrates-to-java-11).
> 
> For the plugin I maintain, I added the following settings in the build file, maybe something similar would work for this plugin.
> 
> ```
> java {
>   targetCompatibility = "11"
>   sourceCompatibility = "11"
> }
> ```

Hi, thank you very much, I will fix this as soon as possible.
