### ISSUE TITLE
使用ExcelReader打开本地.xlsx文档后, 原始文件会被修改

### ISSUE THREAD

**Issue by 1260zqs** [obiscr/ExcelReader#2]
这是一个Reader我不明白在关闭编辑器之后为什么原始文件会被修改

**Comment by obiscr** [comment]
您好，您说的修改是指？

**Comment by 1260zqs** [comment]
表面显示内容没有区别, 在二进制上全部变了, 文件大小也变了
![image](https://github.com/obiscr/ExcelReader/assets/28787010/b26a506f-7717-4c0f-bbd6-125a8e6e1353)
![image](https://github.com/obiscr/ExcelReader/assets/28787010/b9e38740-eaf8-473a-ad35-8e384155f0ed)
![image](https://github.com/obiscr/ExcelReader/assets/28787010/d5bb3b73-1161-44e2-a9f7-0223593980fd)

**Comment by obiscr** [comment]
好的，感谢提供详细的信息，我会进行测试。

**Comment by obiscr** [comment]
这个问题已经被修复，请更新到最新版本 2023.11.1,  谢谢。
