### ISSUE TITLE
Support for IntelliJ IDEA 2023 ?

### ISSUE THREAD

**Issue by juergenzimmermann** [obiscr/ExcelReader#20]
@obiscr Can you give a coarse extimation when a release for IntelliJ 2023 will be available, please? A Beta release of IJ 2023 is available right now.

**Comment by obiscr** [comment]
Based on past experience, it may be in April，

**Comment by obiscr** [comment]
Based on past experience, it may be in April

**Comment by obiscr** [comment]
I will support the eap version in the near future.

**Comment by obiscr** [comment]
@juergenzimmermann The 2023 has been supported. Please update to latest version.

**Comment by juergenzimmermann** [comment]
@obiscr I tried the latest Beta for 2023.1.0: the installation works. However, ExcelReader doesn't show the contents of a CSV file:
![image](https://user-images.githubusercontent.com/734334/225527797-685a1971-1f95-46ac-b53d-91992d116966.png)

**Comment by obiscr** [comment]
This should be a file problem, I test can open csv files.

Please provide us with the desensitized csv file. And check if there is an error log.

**Comment by juergenzimmermann** [comment]
A CSV file is attached.
[adresse.csv](https://github.com/obiscr/ExcelReader/files/10992711/adresse.csv)

**Comment by obiscr** [comment]
Sorry for the late replay, after my troubleshooting, this is a bug in the third hair dependency library.

If you replace the `;` in the file with `,` then the file will be parsed normally.

**Comment by juergenzimmermann** [comment]
@obiscr Why do you stick to POI `4.1.2` from 2020? There is `5.2.3` from September 2022: https://archive.apache.org/dist/poi/release/bin.

**Comment by obiscr** [comment]
I tried the new version before, but it had problems parsing the content and conflicted with another third-party dependency. So I gave up on upgrading.
