### ISSUE TITLE
Support opening file with the Remote File Systems Plugin

### ISSUE THREAD

**Issue by joshuataylor** [obiscr/ExcelReader#3]
## Language barrier

Apologies, I don't speak/read the same language as the author - Google says that the language is Chinese. I will try and ensure that hopefully my text translates well using Google Translate!

Hi!

This plugin works great when you have a file locally, and allows quick reading of Excel files.

Jetbrains has a set of plugins called [Big Data Tools](https://www.jetbrains.com/help/idea/big-data-tools-support.html), with a sub-plugin called [Remote File Systems](https://www.jetbrains.com/help/idea/big-data-tools-remote-file-systems.html) which allows you to see files in a remote file system, such as a S3 compatible bucket.

It seems that it can display files that IntelliJ supports (plain text?) without the IntelliJ Editor, but for certain files (PDF etc) it opens your default program that you view the file with.

When I try an open an Excel file from Remote File Systems without the ExcelReader plugin enabled, IntelliJ opens Excel (my default program).

With the plugin enabled, it returns a popup error `No viewer found for Book1.xlsx` and nothing happens (this file works fine locally).

<img width="417" alt="image" src="https://github.com/obiscr/ExcelReader/assets/225131/a70b47dc-58d2-4a92-b4ad-8b4f6ecbdfdc">

Locally (it's just a test Excel file :)):
<img width="250" alt="image" src="https://github.com/obiscr/ExcelReader/assets/225131/07f9b127-c8aa-4691-8d04-9bf358fe0259">

I think that perhaps there is a new way that Jetbrains handles opens files via the plugin, and there is a new hook or something similar?

> Also, this would make a pretty cool paid feature (I actually didn't realise there was a paid version, I went and bought that to support)!

**Comment by obiscr** [comment]
Hi, please keep focus on ExcelEditor issue [#7](https://github.com/obiscr/ExcelEditor/issues/7).
