### ISSUE TITLE
Plugin incompatible with current build

### ISSUE THREAD

**Issue by ericvpatridge** [obiscr/ExcelReader#4]
This page says the plugin is compatible with 2023.3.2:  https://plugins.jetbrains.com/plugin/14722-excelreader

However, the current build is beyond the supported build.

Here's the message I get when I try to "Install Plugin from Disk":
Plugin 'ExcelReader' (version '2023.11.1-222.232') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is PY-233.13135.95

**Comment by obiscr** [comment]
Thanks for the feedback, I will test it, and by the way, which file did you download for local installation?

**Comment by ericvpatridge** [comment]
Great!  I downloaded the latest one I could find:

- [2023.11.1-222.232](https://plugins.jetbrains.com/plugin/14722-excelreader/versions/stable/436130)
- 2022.2 — 2023.2.6
- Nov 10, 2023

**Comment by obiscr** [comment]
A new version **2024.2.1-233** has been released. Please update to latest version. :D
