### ISSUE TITLE
No sheet tabs

### ISSUE THREAD

**Issue by diveboatslave** [obiscr/ExcelReader#6]
I'm using IntelliJ IDEA 2021.2.3 Ultimate, build 212.5457.46, on Mac OS 10.15.7, and I don't see the worksheet tabs at the bottom of ExcelReader when I open .xslx files.

**Comment by obiscr** [comment]
> I'm using IntelliJ IDEA 2021.2.3 Ultimate, build 212.5457.46, on Mac OS 10.15.7, and I don't see the worksheet tabs at the bottom of ExcelReader when I open .xslx files.

Thank you for your feedback. Can you provide the excel file after desensitization. As far as I know, this problem may also have something to do with the excel editor.

**Comment by kangjiantsui** [comment]
![1639728088(1)](https://user-images.githubusercontent.com/48082892/146510292-88a0e910-49d8-44dc-ab94-a0c7874ecde8.png)
![1639728125(1)](https://user-images.githubusercontent.com/48082892/146510371-7dad2ebf-0d86-48b6-a213-0c15c3578a08.png)
![1639728178(1)](https://user-images.githubusercontent.com/48082892/146510458-e407e5a7-5c3b-49bb-8440-4e43cf8bbcb8.png)
[R_任务限制_TaskLimit.xlsx](https://github.com/obiscr/ExcelReader/files/7733514/R_._TaskLimit.xlsx)

没有下面的sheet

**Comment by obiscr** [comment]
> ![1639728088(1)](https://user-images.githubusercontent.com/48082892/146510292-88a0e910-49d8-44dc-ab94-a0c7874ecde8.png) ![1639728125(1)](https://user-images.githubusercontent.com/48082892/146510371-7dad2ebf-0d86-48b6-a213-0c15c3578a08.png) ![1639728178(1)](https://user-images.githubusercontent.com/48082892/146510458-e407e5a7-5c3b-49bb-8440-4e43cf8bbcb8.png) [R_任务限制_TaskLimit.xlsx](https://github.com/obiscr/ExcelReader/files/7733514/R_._TaskLimit.xlsx)
> 
> 没有下面的sheet

好的，我更新到对应的版本看一下。

**Comment by obiscr** [comment]
> ![1639728088(1)](https://user-images.githubusercontent.com/48082892/146510292-88a0e910-49d8-44dc-ab94-a0c7874ecde8.png) ![1639728125(1)](https://user-images.githubusercontent.com/48082892/146510371-7dad2ebf-0d86-48b6-a213-0c15c3578a08.png) ![1639728178(1)](https://user-images.githubusercontent.com/48082892/146510458-e407e5a7-5c3b-49bb-8440-4e43cf8bbcb8.png) [R_任务限制_TaskLimit.xlsx](https://github.com/obiscr/ExcelReader/files/7733514/R_._TaskLimit.xlsx)
> 
> 没有下面的sheet

根据我刚才测试的情况，并没有测试出什么问题。不过今天会更新一个新版本 2.0.8，支持最新的 2021.3 版本，后续可以更新到 2.0.8再测试一下，看是否还有此问题。感谢反馈！
![issue6](https://user-images.githubusercontent.com/28687074/146629028-3cceaf25-7b17-4517-8b02-428a826ba2ce.gif)

**Comment by kangjiantsui** [comment]
> > ![1639728088(1)](https://user-images.githubusercontent.com/48082892/146510292-88a0e910-49d8-44dc-ab94-a0c7874ecde8.png) ![1639728125(1)](https://user-images.githubusercontent.com/48082892/146510371-7dad2ebf-0d86-48b6-a213-0c15c3578a08.png) ![1639728178(1)](https://user-images.githubusercontent.com/48082892/146510458-e407e5a7-5c3b-49bb-8440-4e43cf8bbcb8.png) [R_任务限制_TaskLimit.xlsx](https://github.com/obiscr/ExcelReader/files/7733514/R_._TaskLimit.xlsx)
> > 没有下面的表
> 
> 根据我刚测试的情况，并没有测试出什么问题。不过今天会更新一个新版本 2.0.8，最新的 2021.3 版本，可以支持更新到 2.0.8 再测试一下，看看还有没有这个问题。反馈！ ![问题 6](https://user-images.githubusercontent.com/28687074/146629028-3cceaf25-7b17-4517-8b02-428a826ba2ce.gif)

更新插件后问题解决了👍👍
