### ISSUE TITLE
How to avoid associating CSV files?

### ISSUE THREAD

**Issue by zhenlingcn** [obiscr/ExcelReader#8]
This is an excellent plugin. However, it seems that it will replace the built-in CSV editor, which causes me to be unable to edit the CSV file. Thus, how to avoid associating CSV files? Thanks!

**Comment by obiscr** [comment]
Thanks for the feedback. this is a good idea. A future release will consider support for file editing. However, the exact release time is not yet known.

Of course if you really need it. I can even come up with a specific version to avoid detection of csv files. This way, you can use the built-in csv editor to work with csv files.

**Comment by obiscr** [comment]
> This is an excellent plugin. However, it seems that it will replace the built-in CSV editor, which causes me to be unable to edit the CSV file. Thus, how to avoid associating CSV files? Thanks!

Thanks for the feedback. this is a good idea. A future release will consider support for file editing. However, the exact release time is not yet known.

Of course if you really need it. I can even come up with a specific version to avoid detection of csv files. This way, you can use the built-in csv editor to work with csv files.

**Comment by obiscr** [comment]
> This is an excellent plugin. However, it seems that it will replace the built-in CSV editor, which causes me to be unable to edit the CSV file. Thus, how to avoid associating CSV files? Thanks!

And you also can remove the registered file type.
![simple](https://user-images.githubusercontent.com/28687074/151704327-8f1a91e3-a50c-4371-9269-94af270bdaa9.png)

`Settings` -> `Editor` -> `File Types` -> **Find the ExcelReader Plugin** -> Remove the **csv**, and save it.
