### ISSUE TITLE
empty result if first row in sheet is empty

### ISSUE THREAD

**Issue by giorgioborri** [obiscr/ExcelReader#9]
Hi, with the plugin version 2.1.2 Tiger 
when I open a xlsx file where the first rows are empty and the header cells are in the next row , in the plugin tab I got an empty result.
 and If the the first columns are empty and in the empty first rows there is some text I got exception.
for exampe: columns A and B are empty, the rows 1,2,3 are empty, in the cell A2 there is some text
and the datas are in the matrix C4:G20 i got an exception

**Comment by obiscr** [comment]
> Hi, with the plugin version 2.1.2 Tiger when I open a xlsx file where the first rows are empty and the header cells are in the next row , in the plugin tab I got an empty result. and If the the first columns are empty and in the empty first rows there is some text I got exception. for exampe: columns A and B are empty, the rows 1,2,3 are empty, in the cell A2 there is some text and the datas are in the matrix C4:G20 i got an exception

Thanks for the feedback, I tested it and it did.
![image](https://user-images.githubusercontent.com/28687074/152627581-4258f5db-ffa1-4c36-aa24-c7166cc0b6ea.png)

At present, the default is to read the header of the first row, and the data after the first row. So I suggest you to modify the table，like this：
![image](https://user-images.githubusercontent.com/28687074/152627613-db4a90ec-a23c-4040-8707-ecbe157c6344.png)

Then it can be read normally.
![image](https://user-images.githubusercontent.com/28687074/152627649-9ebed6c8-c34a-4020-8864-e760d7fd7f0a.png)

**By the way, now only supports regular data. If there is a situation like merging cells. Something could go wrong.**
